### ISSUE TITLE
Minimum number of samples?

### ISSUE THREAD

**Issue by abayega** [Teichlab/SpatialDE#1]
Hi,

we have done a time course experiment similar to the frog Cell paper experiment but we have only 6 samples and no replicates for now. Do you think it's okay to use your tool to look at temporal variation in gene expression?

Thanks

**Comment by vals** [comment]
Hi @abayega,

I haven't tried it with so few samples, it should work though, but might not be sensitive enough for you.

One thing to keep in mind is that with 6 time points short length-scales will always perfectly fit the data, and will always give significant P-values. To avoid this, you can manually specify that the smallest length-scale is covering at least a couple of time points, forcing a couple of observations of evidence for each curve.

The `SpatialDE.run()` function has an argument `kernel_space` which is a dictionary where you can manually specify the grid of length scales to search over. If your time points are `[0.0, 2.0, 4.0, 6.0, 8.0]` for example, you would want to put something like `kernel_space={'SE': np.logspace(np.log10(4.0), np.log10(16.0), 10)}`.

The underlying principle of the method is based on estimating variance and covariance, and estimating variance is generally considered a difficult problem when you have less than ~50 samples. Many differential expression methods do clever things to share information about variance between genes to get better estimates, but this is not done here. This might be a future interesting extension though that I hadn't thought of before.

Let me know how it goes if you try it!

/Valentine
