### ISSUE TITLE
Looks like cellBoundaries.mat is missing from MERFISH

### ISSUE THREAD

**Issue by vipulsinghal02** [Teichlab/SpatialDE#10]
Hello, 

I am trying to run the scripts in this package, and it seems that the file cellBoundaries.mat is missing from the folder 
/Analysis/MERFISH/data/rep6/

I think I have done the git lfs pull correctly... even the pointer to the file is not present in the git repo. 
@vals 
Vipul Singhal

**Comment by vals** [comment]
Hey Vipul,

I don't think I included it, it is pretty large and I only used it to assign cellIDs to RNA, the boundaries themselves are only used implicitly.

I have the boundaries file for rep6 on my computer if you want it. For the other rep's I think you'll need to contact Jeff Moffitt.

**Comment by vipulsinghal02** [comment]
Hey Valentine, 

Hope Pasadena is treating you well :-). 

I think it would be great if you could share the boundaries file for rep 6.

Thanks!!
Vipul
