### ISSUE TITLE
how to pick l in AEH

### ISSUE THREAD

**Issue by jon-xu** [Teichlab/SpatialDE#14]
Hi,

I'm wondering how to pick l in AEH from the result of running:
sign_results['l'].value_counts()

Thanks for clarification!

**Comment by vals** [comment]
You should pick a value that reflects most of the significant genes.

**Comment by jon-xu** [comment]
so in your example:

1.135190    11
1.907609     4
0.675535     4
3.205604     1
Name: l, dtype: int64

How do we derive ~1.5 and choose 1.8, please?
