### ISSUE TITLE
no convergence in AEH

### ISSUE THREAD

**Issue by jon-xu** [Teichlab/SpatialDE#15]
Hi,

My run of AEH ends after 100 rounds without getting converged.

Not sure how to improve this, please?

Thanks!

**Comment by vals** [comment]
Without more information I would suggest running for more iterations.

**Comment by jon-xu** [comment]
I noticed the threshold for convergence was set to 1e-2 in python script aeh.py, although in the example it finishes after more iterations (likely 1e-4).  Maybe different threshold can be chosen to stop convergence before 100 iterations.
