### ISSUE TITLE
Heads-up on git lfs

### ISSUE THREAD

**Issue by gokceneraslan** [Teichlab/SpatialDE#2]
Thanks for nice method & implementation. It'd be great to give new users a heads-up about git lfs. Writing somewhere (maybe `README.rst` or `README.ipynb`) something like

> In order to execute Jupyter notebooks, you must clone the git repository using `git lfs clone`  instead of `git clone`. Alternatively, you can use `git lfs pull`, if you've already cloned it via `git clone`.

would make things easier especially for beginners.

**Comment by vals** [comment]
Hi!

Thanks, that's a good point!

I also have to say, in several projects `git lfs` has been such a headache, I wish I hadn't used it.

**Comment by gokceneraslan** [comment]
git lfs downloads 1.5GB data though, it'd be also difficult without using it .

**Comment by vals** [comment]
Yeah, I think for my next project I'll try https://osf.io/, it seems like a decent solution for "medium size" data.
