### ISSUE TITLE
Cannot pull lfs

### ISSUE THREAD

**Issue by emkahuda** [Teichlab/SpatialDE#27]
Hi,

I want to try running all scripts for the analysis example provided. I tried to follow the steps, including brew installation and git lfs installation as well. It was successful, but there was a problem in cloning the git to my MacBook. I wanted to pull lfs inside the folder (in the Analysis folder) using git pull lfs as mentioned on your Readme file. However, I got this error. Is it my Mac issue or your GitHub account? Could you please help? 
![Screenshot 2022-09-07 at 15 55 34](https://user-images.githubusercontent.com/43750363/188914197-55ec0fc8-9ee0-41bb-9956-642842a9758d.png)

**Comment by Chokerino** [comment]
Same issue here.

**Comment by vals** [comment]
Hi,

As the README file states:

> If you are having problems using git lfs, all the data are available on figshare here: https://figshare.com/articles/software/SpatialDE/17065217

I think it is neither your Mac or Github account, it is merely a problem of git lfs being completely useless.
