### ISSUE TITLE
Softmax instability?

### ISSUE THREAD

**Issue by vals** [Teichlab/SpatialDE#3]
[Reported by David Cook](https://twitter.com/DavidPCook/status/968669816117579776)

![image](https://user-images.githubusercontent.com/668803/36766453-d19d4042-1bea-11e8-8755-62e4eeb5a7bf.png)

**Comment by dpcook** [comment]
Just to record some context here in writing, this occurred when trying to use AEH to find expression patterns along a 2D diffusion map of a ~10,000 scRNA-seq dataset.

[Notebook](https://github.com/dpcook/singlecell_EMT/blob/master/notebooks/spatialDE_diffusion_map.ipynb)
In the notebook I grab the embedding from an AnnData object. Here, I've just included a csv file with the columns X_diffmap1 and X_diffmap2

Data for reproducing the error
1. [Expression matrix (~2Gb; csv format)](https://drive.google.com/file/d/15VlyI8oWtuQG3_QQLwU0TQdn7ykdzISK/view?usp=sharing)
2. [Cell metadata (including diffusion map coordinates)](https://drive.google.com/file/d/1aNlVUmP8I50xY7uumjwOsjDyza0JneRW/view?usp=sharing)
3. [SpatialDE Output](https://drive.google.com/file/d/1I1mTxnuI6px0NxPKs6ThC-ZQPtKLVHNl/view?usp=sharing)
4. [AEH Results (pattern assignment and membership value)](https://drive.google.com/file/d/1CUOuDNPXIyeVYM8b4EN5bxkQkM5h253e/view?usp=sharing)
5. [AEH Pattern values](https://drive.google.com/file/d/1wFK7WFkBJX5jeYsao5onjpJOVwAui1K2/view?usp=sharing)

Let me know if there are any issues accessing everything!

**Comment by vals** [comment]
Wow it's pretty slow with that many cells it turns out!

I can reproduce the problem with a smaller subsample of the data though, so I'll get to looking into that.

**Comment by vals** [comment]
I think I fixed the problem in a stable way. I'm just rerunning your clustering now to make sure the results didn't change too much.

**Comment by vals** [comment]
Hey @dpcook I reran this over the day, now there's no division by 0 error, and the delta_ELBO is properly decreasing.
![image](https://user-images.githubusercontent.com/668803/37318355-44c38130-2627-11e8-982e-0e89b996195d.png)

You would want to run this until delta_ELBO becomes close to 0 though, which will probably take quite some time with this dataset!

I think the patterns I get after 3 iterations are roughly similar to yours though, so I'll push this change to PyPI.

Thanks for the nice report and data needed to debug this!

/Valentine

**Comment by dpcook** [comment]
Thanks for this @vals! Sorry for delayed reply--just got back from vacation after SCB18.

I'll start running it today and will let you know if there are any issues!

**Comment by dpcook** [comment]
Glad to report that after runner for a couple days, it seems to have converged after 99 iterations. 
![image](https://user-images.githubusercontent.com/18197806/37849112-d78d411c-2eac-11e8-8f71-be74d7fad690.png)

**Comment by vals** [comment]
Wow! Thanks for checking.
