### ISSUE TITLE
DEBUG level for logging

### ISSUE THREAD

**Issue by gokceneraslan** [Teichlab/SpatialDE#6]
Hi,

Setting logging verbosity level to DEBUG makes matplotlib.pyplot calls super verbose:

![image](https://user-images.githubusercontent.com/1140359/50378154-13e0b580-05f9-11e9-95d8-43e8f897e606.png)

Does it make sense not to set it by default at all? Relevant line:

https://github.com/Teichlab/SpatialDE/blob/master/Python-module/SpatialDE/base.py#L23

**Comment by vals** [comment]
Ah yes, I've wondered why I've needed to change the logging settings after running SpatialDE tests. I probably just accidentally left the setting there after fixing something a long time ago. Thanks for pointing it out!
